# Generated by Django 3.2.8 on 2021-11-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211024_1822'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kcalamount',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0.0)), name='amount_gt_0'),
        ),
    ]
