# Generated by Django 3.2.6 on 2021-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=777, max_length=12),
            preserve_default=False,
        ),
    ]
