# Generated by Django 3.2.6 on 2021-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_has_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_notifications',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
