# Generated by Django 3.2.6 on 2021-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211126_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notification_count',
        ),
    ]
