# Generated by Django 3.2.9 on 2021-12-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_notification_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KCalAmount',
        ),
    ]
