# Generated by Django 3.2.10 on 2021-12-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='parent',
        ),
    ]
