# Generated by Django 3.2.10 on 2022-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_directmessage_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_pod_plus_member',
            field=models.BooleanField(default=False),
        ),
    ]
