# Generated by Django 3.2.8 on 2021-11-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='responded_users',
        ),
    ]
