# Generated by Django 3.2.6 on 2021-11-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20211103_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likes',
        ),
    ]
