# Generated by Django 3.2.9 on 2021-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20211103_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intLikeCount',
            field=models.IntegerField(default=0),
        ),
    ]
