# Generated by Django 3.2.9 on 2021-11-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_post_intlikecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intLikeCount',
        ),
    ]
