# Generated by Django 3.2.6 on 2021-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
