# Generated by Django 3.2.6 on 2021-11-07 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0014_alter_post_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'title')},
        ),
    ]
