# Generated by Django 3.2.9 on 2021-12-01 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0017_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='responded_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequestForHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_request_help_set', to=settings.AUTH_USER_MODEL)),
                ('responded_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'title')},
            },
        ),
    ]
