# Generated by Django 3.2.6 on 2021-12-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0021_auto_20211205_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
