# Generated by Django 3.2.6 on 2021-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211207_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_model_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
