# Generated by Django 3.2.9 on 2021-12-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211208_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_id',
            new_name='related_model_id',
        ),
    ]
