# Generated by Django 3.2.9 on 2021-12-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_related_id_notification_related_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_model_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_model_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_url',
            field=models.URLField(null=True),
        ),
    ]
