# Generated by Django 3.2.9 on 2021-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211208_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_url',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_reverse',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_reverse_args',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
