# Generated by Django 3.2.10 on 2021-12-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_directmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
