# Generated by Django 3.2.10 on 2021-12-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20211220_1706'),
        ('communities', '0023_auto_20211220_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20211220_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_post_set', to='communities.post'),
        ),
        migrations.AlterField(
            model_name='notificationpost',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notification_post_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationpost',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification_post_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_help_request_set', to='newsfeed.helprequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notification_help_request_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification_help_request_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
