# Generated by Django 3.2.10 on 2021-12-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211220_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipofday',
            old_name='text_content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='notificationhelprequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationpost',
            name='message',
        ),
        migrations.AddField(
            model_name='notificationhelprequest',
            name='text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
