# Generated by Django 3.2.10 on 2021-12-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notificationuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
