# Generated by Django 3.2.6 on 2021-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofday',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
