# Generated by Django 3.2.6 on 2021-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tipofday_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofday',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
