# Generated by Django 3.2.10 on 2022-01-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_feedbackhelprequestoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackhelprequestoffer',
            old_name='feedback_chocies',
            new_name='feedback_choice',
        ),
    ]
