# Generated by Django 3.2.10 on 2022-01-17 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_rename_feedback_chocies_feedbackhelprequestoffer_feedback_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_dm_author_set', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_dm_partner_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'name')},
            },
        ),
    ]
