# Generated by Django 3.2.9 on 2022-01-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220119_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DM',
        ),
    ]
