# Generated by Django 3.2.9 on 2022-01-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dm_set', to='core.roomdm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationdm',
            name='dm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dm_set', to='core.dm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationdm',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notification_dm_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationdm',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification_dm_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
