# Generated by Django 3.2.9 on 2022-01-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220119_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_set', to='core.roomdm'),
        ),
    ]
