# Generated by Django 3.2.10 on 2022-01-22 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_alter_dm_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('feedback_choice', models.CharField(blank=True, choices=[(0, 'offensive'), (1, 'inappropriate'), (2, 'no reason'), (3, 'other')], max_length=2, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_help_request_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
