# Generated by Django 3.2.6 on 2021-12-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0002_helprequestoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequestoffer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_request_offer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
