# Generated by Django 3.2.6 on 2021-12-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_helprequestoffer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequestoffer',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_request_offer_set', to='newsfeed.helprequest'),
        ),
    ]
