# Generated by Django 3.2.6 on 2021-12-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_alter_helprequestoffer_help_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='responded_users',
            new_name='accepted_user',
        ),
    ]
