# Generated by Django 3.2.6 on 2021-12-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0005_rename_responded_users_helprequest_accepted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='accepted_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_help_request_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_help_request_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
