# Generated by Django 3.2.10 on 2021-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_helprequest_accept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
