# Generated by Django 3.2.10 on 2021-12-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0008_alter_helprequest_accept_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='accepted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_help_request_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
