# Generated by Django 3.2.10 on 2021-12-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='date',
            new_name='pub_date',
        ),
    ]
